

MODEL:
  LOAD_CHECKPOINT: /mnt/gpid07/users/adria.caelles/output_dir/T01.13_FinetuneT01-11_LongerClip/checkpoints/T01.13_FinetuneT01-11_LongerClip_epoch_2_BEST.pth
  RUNTIME_CONFIG:
    # Epoch at which the actions will be done
    FreezeRVOSEncoder: 0
    UnfreezeRVOSEncoder: -1
    UsePreviousInferenceMask: 0

OAGCNN:
  MESSAGE_PASSING_STEPS: 1
  USE_TEMPORAL_FEATURES: True
  BACKPROPAGATE_FEATURES: True
  USE_PREVIOUS_INFERENCE_MASK: True
  # Whether to backpropagate gradients through the predicted mask or use just the mask itself (data)
  # Keeping gradient will increase memory usage
  BACKPROPAGATE_PREDICTED_MASKS: True
  NUM_CLASSES: 1
  # MaskedNLLLoss, MaskedBCELoss, SoftIoULoss
  LOSS_FUNCTION: SoftIoULoss
  
  ARCH:
    FEATURE_EXTRACTOR: RVOSFeatureExtractor
    
    GRAPH:
      MASK_ENCODING_MODULE: MaskEncoderOneStage
      # GCNNSimple, GCNNConvBlocks, GRUGCNN
      GCNN_MODULE: GRUGCNN
      READ_OUT: ReadOutWithRefinement


MaskEncoderOneStage:
  OUT_CHANNELS: 16

RVOSFeatureExtractor:
  RVOS_ENCODER:
    BACKBONE: ResNet101
    LOAD_PRETRAINED: True
    HIDDEN_SIZE: 128
    KERNEL_SIZE: 3
  
  RVOS_ADAPTER:
    USED_FEATURES: [x5, x4, x3, x2]
    # 1 for not changing
    CHANNELS_FACTOR_REDUCTION: 2
    # With respect to input DATA.IMAGE_SIZE!
    SPATIAL_SCALE_FACTOR: 2
  
  #Should be moved to another place
  RVOS_HEAD:
    HIDDEN_SIZE: 32
    DROPOUT: 0.25
    OUT_CHANNELS: 8

DATA:
  NUM_WORKERS: 5
  SHUFFLE: True
  DROP_LAST: True
  BATCH_SIZE: 4
  VAL_BATCH_SIZE: 1
  CLIP_LENGTH: 10
  MAX_NUM_OBJ: 10
  IMAGE_SIZE: (256, 448)
  AUGMENTATION: True

AUG_TRANSFORMS:
  ROTATION: 10
  TRANSLATION: 0.1
  SHEAR: 0.1
  ZOOM: 0.7

SOLVER:
  OPTIMIZER: Adam
  LR: 0.001
  WEIGHT_DECAY: 0.0001
  NUM_EPOCHS: 10
  CHECKPOINTER:
    SAVE_ALWAYS: True
    PATIENCE: 10
    PATIENCE_DELTA: 0.
  USE_SCHEDULER: True
  LR_SCHEDULER:
    NAME: "MultiStepLR"
    STEPS: [6, 9]
    STEP_SIZE: 0.1
  EVALUATION_METRIC: "loss"

DATASETS:
  TRAIN: YouTubeVOS
  TRAIN_SPLIT: train
  VAL: YouTubeVOS
  VAL_SPLIT: val
  TEST: YouTubeVOS
  TEST_SPLIT: test

PREDICTOR:
  USE_GPU: True
  OVERLAY_MASKS: False
  INSTANCE_RESULTS: False
  PREPARE_SUBMISSION_RESULTS: True
  USE_METADATA_GT_INFO: True

GENERAL_CONFIG:
  TRAIN_NAME: T01.13_FinetuneT01-11_LongerClip
  PRINT_EVERY: 5
  USE_GPU: True